// ignore_for_file: type=lint
//
// COMMITTED TEMPLATE — documents the shape of `lib/firebase_options.dart`,
// which is generated by the FlutterFire CLI and gitignored.
//
// A fresh clone will not compile until that file exists. Generate it:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
// Select the GSUhub Firebase project and tick **android** and **web**
// only — the project targets Android 8.0+ and modern browsers
// (manuscript §3.2), and generating iOS/desktop options would add
// platforms nothing builds for.
//
// Do not hand-edit the generated file; re-run `flutterfire configure` if
// the Firebase project changes. See docs/firebase_setup.md.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'GSUhub targets Android and web only. Re-run `flutterfire '
          'configure` if another platform is genuinely needed.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'GENERATED_WEB_API_KEY',
    appId: 'GENERATED_WEB_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'GENERATED_PROJECT_ID',
    authDomain: 'GENERATED_PROJECT_ID.firebaseapp.com',
    storageBucket: 'GENERATED_PROJECT_ID.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'GENERATED_ANDROID_API_KEY',
    appId: 'GENERATED_ANDROID_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'GENERATED_PROJECT_ID',
    storageBucket: 'GENERATED_PROJECT_ID.firebasestorage.app',
  );
}
