import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../../core/enums/inventory_transaction_type.dart';
import '../../../../core/utils/firestore_converters.dart';

/// An `inventory_transactions` document — one immutable entry in the
/// inventory history log (manuscript §3.4: the system "records the
/// transaction in the inventory history log" whenever stock moves).
///
/// **This collection is append-only.** Every change to
/// `inventory_items.quantityAvailable` must be accompanied by one of these
/// records, and a record, once written, is never edited or deleted.
/// That invariant is enforced in three places:
///
/// 1. **This class has no `copyWith`** — deliberately. Every other model
///    in the codebase has one; its absence here is the signal. There is no
///    supported way to derive a modified transaction, because modifying a
///    ledger entry is not a legal operation.
/// 2. **The repository contract** exposes no update or delete method for
///    transactions.
/// 3. **Security rules** allow `create` on this collection but deny
///    `update` and `delete` to every role, including administrators.
///
/// [quantityBefore] and [quantityAfter] are recorded on the entry itself
/// rather than recomputed, so the ledger stays auditable even if a stock
/// figure is later corrected by an `adjustment` entry — you can always
/// reconstruct what the balance was believed to be at each point.
class InventoryTransaction {
  InventoryTransaction({
    required this.id,
    required this.inventoryItemId,
    required this.itemName,
    required this.type,
    required this.quantity,
    required this.quantityBefore,
    required this.quantityAfter,
    required this.performedBy,
    required this.performedAt,
    this.workOrderId,
    this.accomplishmentReportId,
    this.notes,
  }) {
    FirestoreConverters.validateNotBlank(inventoryItemId, 'inventoryItemId');
    FirestoreConverters.validateNotBlank(itemName, 'itemName');
    FirestoreConverters.validateNotBlank(performedBy, 'performedBy');
    if (quantity <= 0) {
      throw ArgumentError.value(
        quantity,
        'quantity',
        'Transaction quantity must be greater than zero; direction is '
            'carried by the transaction type, not the sign',
      );
    }
    FirestoreConverters.validateNonNegative(quantityBefore, 'quantityBefore');
    FirestoreConverters.validateNonNegative(quantityAfter, 'quantityAfter');
  }

  factory InventoryTransaction.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data() ?? <String, dynamic>{};
    return InventoryTransaction(
      id: doc.id,
      inventoryItemId: FirestoreConverters.require<String>(
        data,
        'inventoryItemId',
      ),
      itemName: FirestoreConverters.require<String>(data, 'itemName'),
      type: FirestoreConverters.requireEnum(
        data,
        'type',
        InventoryTransactionType.fromId,
      ),
      quantity: FirestoreConverters.require<num>(data, 'quantity').toDouble(),
      quantityBefore: FirestoreConverters.require<num>(
        data,
        'quantityBefore',
      ).toDouble(),
      quantityAfter: FirestoreConverters.require<num>(
        data,
        'quantityAfter',
      ).toDouble(),
      workOrderId: FirestoreConverters.optional<String>(data, 'workOrderId'),
      accomplishmentReportId: FirestoreConverters.optional<String>(
        data,
        'accomplishmentReportId',
      ),
      notes: FirestoreConverters.optional<String>(data, 'notes'),
      performedBy: FirestoreConverters.require<String>(data, 'performedBy'),
      performedAt: FirestoreConverters.requireDate(data, 'performedAt'),
    );
  }

  final String id;
  final String inventoryItemId;

  /// DENORMALIZED from `inventory_items.name` — a ledger must stay
  /// readable forever, including after an item is renamed or removed.
  final String itemName;

  final InventoryTransactionType type;

  /// Always positive. Direction is carried by [type.isDeduction], not by
  /// the sign, so a malformed negative quantity can't silently invert a
  /// movement.
  final double quantity;

  final double quantityBefore;
  final double quantityAfter;

  /// The work order this movement served, when applicable.
  final String? workOrderId;

  /// Set on `consumption` entries generated by the automatic deduction
  /// that runs when an accomplishment report is submitted. Doubles as the
  /// idempotency key for that deduction.
  final String? accomplishmentReportId;

  final String? notes;
  final String performedBy;
  final DateTime performedAt;

  Map<String, dynamic> toFirestore() => {
    'inventoryItemId': inventoryItemId,
    'itemName': itemName,
    'type': type.id,
    'quantity': quantity,
    'quantityBefore': quantityBefore,
    'quantityAfter': quantityAfter,
    'workOrderId': workOrderId,
    'accomplishmentReportId': accomplishmentReportId,
    'notes': notes,
    'performedBy': performedBy,
    'performedAt': Timestamp.fromDate(performedAt),
  };

  // Intentionally no copyWith — see the class doc comment. A ledger entry
  // is not editable.

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryTransaction &&
          other.id == id &&
          other.inventoryItemId == inventoryItemId &&
          other.itemName == itemName &&
          other.type == type &&
          other.quantity == quantity &&
          other.quantityBefore == quantityBefore &&
          other.quantityAfter == quantityAfter &&
          other.workOrderId == workOrderId &&
          other.accomplishmentReportId == accomplishmentReportId &&
          other.notes == notes &&
          other.performedBy == performedBy &&
          other.performedAt == performedAt;

  @override
  int get hashCode => Object.hash(
    id,
    inventoryItemId,
    itemName,
    type,
    quantity,
    quantityBefore,
    quantityAfter,
    workOrderId,
    accomplishmentReportId,
    notes,
    performedBy,
    performedAt,
  );

  @override
  String toString() =>
      'InventoryTransaction(id: $id, item: $itemName, type: $type, '
      'quantity: $quantity, $quantityBefore -> $quantityAfter)';
}
